## MPH configuration

points: 700
threads: 2
coord1: "x"
coord2: "y"
parameter: "codensity"
homology: 1
k_family: 1
plot_indices: [1, 1]
resolution: 50
RipsMax: 1
grid_step_size: 0.01
supervised: True