## Pipeline configuration

# MPH configuration
mph:
  contours: True
  points: 700
  threads: 2
  coord1: "x"
  coord2: "y"
  parameter: "codensity"
  homology: 1
  k_family: 1
  plot_indices: [1, 1]
  resolution: 50
  RipsMax: 1
  grid_step_size: 0.01

# Model configuration
model:
  modelling: False
  test_ratio: 0.2
  pretrained: False
  pretrained_model_file_path: null
  supervised: True
  model_to_train_file: "cnn.py"

# Output configuration
output:
  models_directory_path: "../outputs/models/"
  training_directory_path: "../outputs/training/"
  summaries_directory_path: "../outputs/summaries/"