# Data configuration
data:
  raw_data_directory_path: "../data/raw/test_data/"
  processed_data_directory_path: "../data/processed/test_data/"
  label_file: "../data/raw/labels/test_data.csv"

# MPH configuration
mph:
  contours: True
  threads: 14
  coord1: "x"
  coord2: "y"
  parameter: "Oxygen"
  RipsMax: 40
  alpha: 5
  homology: 1
  k_family: 1
  resolution: 50
  grid_step_size: 0.4
  plot_indices: [1, 1]

# Model configuration
model:
  modelling: False
  test_ratio: 0.2
  pretrained: False
  pretrained_model_file_path: null
  supervised: True
  model_to_train_file: "cnn.py"

# Output configuration
output:
  models_directory_path: "../outputs/models/"
  training_directory_path: "../outputs/training/"
  summaries_directory_path: "../outputs/summaries/"